languageCode = "en-us"
title = "Just a Blog in the Park"
baseUrl = "http://justabloginthepark.com/"
log = true
copyright = "&copy; <a href=\"https://github.com/Artiavis\">Jeff Rabinowitz</a>, 2019"
titleCaseStyle = "Chicago"
# enableGitInfo = true

defaultLayout = "post"

paginate = 5
theme = "hemingway"
# googleAnalytics = "UA-45496110-1"
disqusShortname = "justabloginthepark"
verbose = true
verboseLog = true

[privacy]
[privacy.disqus]
  disable = false
[privacy.googleAnalytics]
  anonymizeIP = true
  disable = false
  respectDoNotTrack = true
  useSessionStorage = true
[privacy.instagram]
  disable = false
  simple = true
[privacy.twitter]
  disable = false
  enableDNT = true
  simple = true
[privacy.vimeo]
  disable = false
  simple = true
[privacy.youtube]
  disable = false
  privacyEnhanced = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:year/:month/:day/:title/"
  page = "/:slug/"

[params]
  author = "Jeff Rabinowitz"
  date_format = "Mon Jan 02, 2006"
  Title = "Just a Blog in the Park"
  # sharingicons = false
  disable_sri = true
  hljs_version = "9.12.0"
  fa_version = "5.1.0"

  [params.highlight]
  # style = "github"
  languages = ["bash", "clojure", "cs", "cpp", "css", "fsharp", "kotlin", "javascript", "ini",
               "java", "json", "markdown", "python", "ruby", "scala", "scheme", "sql", "tex"]

  [[params.social]]
  url = "/photos"
  fa_prefix = "fas"
  fa_icon = "fa-camera"

  [[params.social]]
  url = "/tags"
  fa_prefix = "fas"
  fa_icon = "fa-tags"

  [[params.social]]
  url = "https://github.com/Artiavis"
  fa_prefix = "fab"
  fa_icon = "fa-github"

  [[params.social]]
  url = "https://linkedin.com/in/JeffreyCRabinowitz"
  fa_prefix = "fab"
  fa_icon = "fa-linkedin"

  [[params.social]]
  url = "https://www.dropbox.com/s/f71ni06ghor76d3/jeff_rabinowitz_resume_2018_03_24.pdf?dl=1"
  fa_prefix = "fas"
  fa_icon = "fa-file-pdf"

  [[params.social]]
  url = "/index.xml"
  fa_prefix = "fas"
  fa_icon = "fa-rss-square"

