languageCode = "en-us"
title = "Just a Blog in the Park"
baseUrl = "https://www.justabloginthepark.com"
log = true
copyright = "&copy; <a href=\"https://github.com/Artiavis\">Jeff Rabinowitz</a>, 2025"
titleCaseStyle = "Chicago"
# enableGitInfo = true

defaultLayout = "post"

[pagination]
pagerSize = 5
theme = "hemingway"
# googleAnalytics = "UA-45496110-1"
disqusShortname = "justabloginthepark"
verbose = true
verboseLog = true

[privacy]
[privacy.disqus]
  disable = true
[privacy.instagram]
  disable = false
  simple = true
[privacy.x]
  disable = false
  enableDNT = true
  simple = true
[privacy.vimeo]
  disable = false
  simple = true
[privacy.youtube]
  disable = false
  privacyEnhanced = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:year/:month/:day/:title/"
  page = "/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"

[imaging]
resampleFilter = "Lanczos"
quality = 90
anchor = "center"

[params]
  author = "Jeff Rabinowitz"
  date_format = "Mon Jan 02, 2006"
  Title = "Just a Blog in the Park"
  # sharingicons = false
  disable_sri = true
  hljs_version = "9.15.10"
  fa_version = "5.1.0"

  [[params.social]]
  label = "Photos"
  url = "/photos"
  fa_prefix = "fas"
  fa_icon = "fa-camera"

  [[params.social]]
  label = "Tags"
  url = "/tags"
  fa_prefix = "fas"
  fa_icon = "fa-tags"

  [[params.social]]
  label = "GitHub"
  url = "https://github.com/Artiavis"
  fa_prefix = "fab"
  fa_icon = "fa-github"

  [[params.social]]
  label = "LinkedIn"
  url = "https://linkedin.com/in/JeffreyCRabinowitz"
  fa_prefix = "fab"
  fa_icon = "fa-linkedin"

  [[params.social]]
  label = "Resume"
  url = "https://www.dropbox.com/scl/fi/hqyp5rfjmonlzgatrdril/jeff_rabinowitz_resume_winter_2023.pdf?rlkey=oqs7wzuzc0xk8rthx3y6quz4g&dl=0"
  fa_prefix = "fas"
  fa_icon = "fa-file-pdf"

  [[params.social]]
  label = "Subscribe"
  url = "/index.xml"
  fa_prefix = "fas"
  fa_icon = "fa-rss-square"

